# Generated by Django 5.2 on 2025-10-24 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scriptin (XSS)'), ('csrf', 'CSRF Protection'), ('authentication', 'Authentication'), ('encryption', 'Encryption')], max_length=50)),
                ('description', models.TextField()),
                ('vulnerable_code', models.TextField(help_text='Vulnerable code example')),
                ('secure_code', models.TextField(help_text='Secure code example')),
                ('explanation', models.TextField(help_text='Detailed Explanation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security_demos',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_security_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
